obj-y += axp-mfd.o

#axp 199
#Make this built-in, so that it will be loaded before I2C driver
obj-$(CONFIG_AW_AXP15) += axp15-board.o
obj-$(CONFIG_AW_AXP15) += axp15-gpio.o
obj-$(CONFIG_AW_AXP15) += axp15-regu.o
obj-$(CONFIG_AW_AXP15) += axp15-sply.o
obj-$(CONFIG_AW_AXP15) += virtual15.o
obj-$(CONFIG_AW_AXP15) += virtual15_dev.o


obj-$(CONFIG_AW_AXP20) += axp20-board.o
obj-$(CONFIG_AW_AXP20) += axp20-regu.o
obj-$(CONFIG_AW_AXP20_OCV) += axp20-sply.o
obj-$(CONFIG_AW_AXP20_COU) += axp20-sply-cou.o
obj-$(CONFIG_AW_AXP20) += axp20-gpio.o
obj-$(CONFIG_AW_AXP20) += virtual20.o
obj-$(CONFIG_AW_AXP20) += virtual20_dev.o
