obj-$(CONFIG_SND_SUN7I_SOC_HDCP_INTERFACE) += sun7i-hdcp.o
obj-$(CONFIG_SND_SUN7I_SOC_HDCP_INTERFACE) += sun7i-hdcpdma.o
obj-$(CONFIG_SND_SUN7I_SOC_HDCP_INTERFACE) += sndhdcp.o
obj-$(CONFIG_SND_SUN7I_SOC_HDCP_INTERFACE) += sun7i-sndhdcp.o

 
