
obj-$(CONFIG_SND_SUN7I_SOC_HDMIAUDIO) += sun7i-hdmiaudio.o
obj-$(CONFIG_SND_SUN7I_SOC_HDMIAUDIO) += sun7i-hdmipcm.o
obj-$(CONFIG_SND_SUN7I_SOC_HDMIAUDIO) += sndhdmi.o
obj-$(CONFIG_SND_SUN7I_SOC_HDMIAUDIO) += sun7i-sndhdmi.o
 
