

obj-$(CONFIG_SND_SUN7I_SOC_SPDIF) += sun7i_spdif.o
obj-$(CONFIG_SND_SUN7I_SOC_SPDIF) += sun7i_spdma.o
obj-$(CONFIG_SND_SUN7I_SOC_SPDIF) += sndspdif.o
obj-$(CONFIG_SND_SUN7I_SOC_SPDIF) += sun7i_sndspdif.o


