# Copyright 2006 The Android Open Source Project

LOCAL_CFLAGS += -DCONFIG_CTRL_IFACE_CLIENT_DIR=\"/data/misc/wifi/sockets\"
LOCAL_CFLAGS += -DCONFIG_CTRL_IFACE_CLIENT_PREFIX=\"wpa_ctrl_\"

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif
ifdef WIFI_DRIVER_FW_PATH_STA
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_STA=\"$(WIFI_DRIVER_FW_PATH_STA)\"
endif
ifdef WIFI_DRIVER_FW_PATH_AP
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_AP=\"$(WIFI_DRIVER_FW_PATH_AP)\"
endif
ifdef WIFI_DRIVER_FW_PATH_P2P
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_P2P=\"$(WIFI_DRIVER_FW_PATH_P2P)\"
endif
ifdef WIFI_DRIVER_FW_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_PARAM=\"$(WIFI_DRIVER_FW_PATH_PARAM)\"
endif

# realtek usb wifi module-8188cus/8192cu
ifeq ($(SW_BOARD_USR_WIFI), rtl8192cu)
LOCAL_CFLAGS += -DRTL_8192CU_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

# realtek usb wifi module-8192eu
ifeq ($(SW_BOARD_USR_WIFI), rtl8192eu)
LOCAL_CFLAGS += -DRTL_8192EU_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

# realtek usb wifi module-new
ifeq ($(SW_BOARD_USR_WIFI), rtl8188eu)
LOCAL_CFLAGS += -DRTL_8188EU_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

# realtek sdio wifi+bt module
ifeq ($(SW_BOARD_USR_WIFI), rtl8723as)
LOCAL_CFLAGS += -DRTL_8723AS_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

# realtek usb wifi+bt module
ifeq ($(SW_BOARD_USR_WIFI), rtl8723au)
LOCAL_CFLAGS += -DRTL_8723AU_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

# realtek sdio wifi module
ifeq ($(SW_BOARD_USR_WIFI), rtl8189es)
LOCAL_CFLAGS += -DRTL_8189ES_WIFI_USED
LOCAL_CFLAGS += -DRTL_WIFI_VENDOR
endif

LOCAL_SRC_FILES += wifi/wifi.c

LOCAL_SHARED_LIBRARIES += libnetutils
