obj-$(CONFIG_SND_SUN7I_SOC_PCM_INTERFACE) += sun7i-pcm.o
obj-$(CONFIG_SND_SUN7I_SOC_PCM_INTERFACE) += sun7i-pcmdma.o
obj-$(CONFIG_SND_SUN7I_SOC_PCM_INTERFACE) += sndpcm.o
obj-$(CONFIG_SND_SUN7I_SOC_PCM_INTERFACE) += sun7i-sndpcm.o
 
