#
# Makefile for the sw_touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SW_TOUCHSCREEN_FT5X_TS)       += ft5x_ts.o
ft5x_ts-objs := ft5x02_config.o ini.o ft5x.o

